kind: pipeline
name: default 
steps:

  - name: php
    image: plugins/docker
    settings:
      repo: beamaustralia/php
      username:
        from_secret: DOCKER_USERNAME
      password:
        from_secret: DOCKER_PASSWORD
      tags: [ '7.3.3' ]      
    