kind: pipeline
name: default
steps:
  # -----------------------
  #
  # Disabled builds waiting for `buildx` support
  # - Manual builds. See README.md
  #
  # -----------------------

  # - name: publish
  #   image: plugins/docker
  #   settings:
  #     repo: beamaustralia/php
  #     tags: ["latest", "${DRONE_TAG=${DRONE_COMMIT}}"]
  #     username:
  #       from_secret: docker_username
  #     password:
  #       from_secret: docker_password

  # - name: publish.xdebug
  #   image: plugins/docker
  #   settings:
  #     repo: beamaustralia/php
  #     dockerfile: Dockerfile-xdebug
  #     tags: ["xdebug", "${DRONE_TAG=${DRONE_COMMIT}}-xdebug"]
  #     username:
  #       from_secret: docker_username
  #     password:
  #       from_secret: docker_password
