kind: pipeline
name: default 
steps:

  - name: php-cli
    image: plugins/docker
    settings:
      repo: beamaustralia/php
      dockerfile: Dockerfile.php-cli
      username:
        from_secret: DOCKER_USERNAME
      password:
        from_secret: DOCKER_PASSWORD
      tags: [ '7.3.3-cli' ]

  - name: php-fpm
    image: plugins/docker
    settings:
      repo: beamaustralia/php
      dockerfile: Dockerfile.php-fpm
      username:
        from_secret: DOCKER_USERNAME
      password:
        from_secret: DOCKER_PASSWORD
      tags: [ '7.3.3-fpm' ]      
    