kind: pipeline
name: default
steps:

  - name: publish
    image: plugins/docker
    settings:
      repo: beamaustralia/php
      tags: ['5.6']
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
