FROM beamaustralia/php:latest

#
#--------------------------------------------------------------------------
# Install PHP dependencies and extensions
#--------------------------------------------------------------------------
#

RUN apk add --no-cache --virtual .build-deps $PHPIZE_DEPS \
    && pecl install xdebug \
    && docker-php-ext-enable xdebug \
    && apk del -f .build-deps \
    && apk add --no-cache git