#!/bin/bash

set -e

if [ "$PLATFORM_ENV" = "production" ] ||  [ "$PLATFORM_ENV" = "staging" ]; then

    php artisan flex:cache

    echo 'opcache.validate_timestamps=0' >> /usr/local/etc/php/conf.d/php-fpm.ini

fi
