#!/bin/bash

set -e

echo "======================"
echo "======================"

printenv

echo "======================"
echo "======================"

if [ "$PLATFORM_ENV" = "production" ] ||  [ "$PLATFORM_ENV" = "staging" ]; then

    php artisan config:cache

    echo 'opcache.validate_timestamps=0' >> /usr/local/etc/php/conf.d/php-fpm.ini

fi
